name: Autocommunicate Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      repo-type:
        description: "Repo type {all,imagestreams,tempelates}"
        required: true
        default: "all"

jobs:
  workflow-autocommunicate:
    name: Workflow Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.x Part 1
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set up Python 3.x Part 2
        run: |
          # set up python requirements and scripts
          python3 -m venv ve1
          cd scripts && ../ve1/bin/pip3 install -r requirements.txt && cd ..
          cd scripts && ../ve1/bin/python3 setup.py install && cd ..
      
      - name: Auto Communicate
        id: auto_communicate
        env:
          github_token: ${{secrets.GITHUB_TOKEN}}
        run: |
          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
            if [[ "${{github.event.inputs.repo-type}}" == "all" ]]; then
              ve1/bin/python3 create_issue.py  --repoType=all 
            elif [[ "${{github.event.inputs.repo-type}}" == "templates" ]]; then
              ve1/bin/python3 create_issue.py  --repoType=templates 
            elif [[ "${{github.event.inputs.repo-type}}" == "imagestreams" ]]; then
              ve1/bin/python3 create_issue.py  --repoType=imagestreams