name: Autocommunicate Workflow

on:
  workflow_dispatch:
    inputs:
      repo-type:
        description: "Repo type {all,imagestreams,templates,testimagestreams,testtemplates,testall}"
        required: true
        default: "test"

jobs:
  workflow-autocommunicate:
    name: Workflow Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.x Part 1
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set up Python 3.x Part 2
        run: |
          # set up python requirements and scripts
          python3 -m venv ve1
          cd scripts && ../ve1/bin/pip3 install -r requirements.txt && cd ..
          cd scripts && ../ve1/bin/python3 setup.py install && cd ..
      
      - name: Auto Communicate
        id: auto_communicate
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          if [[ "${{github.event.inputs.repo-type}}" == "all" ]]; then
            ve1/bin/python3 scripts/library.py  --repoType=all 
          elif [[ "${{github.event.inputs.repo-type}}" == "templates" ]]; then
            ve1/bin/python3 scripts/library.py  --repoType=templates 
          elif [[ "${{github.event.inputs.repo-type}}" == "imagestreams" ]]; then
            ve1/bin/python3 scripts/library.py  --repoType=imagestreams
          elif [[ "${{github.event.inputs.repo-type}}" == "testimagestreams" ]]; then
            ve1/bin/python3 scripts/library.py  --repoType=testimagestreams
          elif [[ "${{github.event.inputs.repo-type}}" == "testtemplates" ]]; then
            ve1/bin/python3 scripts/library.py  --repoType=testtemplates
          elif [[ "${{github.event.inputs.repo-type}}" == "testall" ]]; then
            ve1/bin/python3 scripts/library.py  --repoType=testall
          fi